Feat: ExitFee in percentage logic move to contract.
bobanetwork/light-bridge pull request #44
Opened 2024-10-14 15:00 UTC by sk-enya

- Added mapping variable for percentExitFee `{sourceChainId} => {percentExitFee}`
- Added variable to record the collectedFee.
- Event to capture the PercentExitFee or change
- Function to calculate the amountAfterFee deduction with input as amount and sourceChainId.
- update disburseAsset fn to use the calculateAmountAfterFee and fee deducted to keep record.
- function to set PercentExitFee corresponding to sourceChainId only owner can set it.
- Added Unit Test 🧪 
- unit test cases for calculateAmountAfterFee
- Unit test validate contract deduction while disburseAsset
- Cleanup deduct exit fee logic from service along with test.

2024-10-14 15:13 UTC, wsdt commented on contracts/LightBridge.sol
> +            feeCollected += fee;
this might be semantically wrong for my understanding as we do collect fees for different assets with the same percentage right now. Means this way 1 unit might be 1 BOBA or 1 ETH here for example

2024-10-14 15:19 UTC, boyuan-chen commented on contracts/LightBridge.sol
> +            feeCollected += fee;
@sk-enya This needs to be fixed.

2024-10-15 14:19 UTC, sk-enya commented on contracts/LightBridge.sol
> +            feeCollected += fee;
So do we have to save the record with respect to tokens?

```solidity
maping(address => uint256) public tokenFeeCollect
```

2024-10-15 14:37 UTC, wsdt commented on contracts/LightBridge.sol
> +            feeCollected += fee;
I think we could also just emit a event to declare the collected fee and we run a graphql query afterwards. 

What do you think @boyuan-chen

2024-10-15 14:45 UTC, boyuan-chen commented on contracts/LightBridge.sol
> +            feeCollected += fee;
Recording it is easier

2024-10-15 14:49 UTC, sk-enya commented on contracts/LightBridge.sol
> +            feeCollected += fee;
@wsdt thoughts make sense to me, as it's just analytics info so better to move away from contract state and can query via subgraphs !

@boyuan-chen please share your thoughts would look into implementing that way!

2024-10-15 15:02 UTC, sk-enya commented on contracts/LightBridge.sol
> +            feeCollected += fee;
okay!

2024-10-18 21:35 UTC, sk-enya commented on contracts/LightBridge.sol
> +            feeCollected += fee;
changes done!

2024-10-19 14:41 UTC, wsdt commented on contracts/LightBridge.sol
> +        uint256 _fee = _amount * percentFee / 10000;
```suggestion
        uint256 _fee = _amount * percentFee / 10_000; 
```

2024-10-19 14:42 UTC, wsdt commented on contracts/LightBridge.sol
> +    function setPercentExitFee(uint256 _percentExitFee, uint32 _sourceChainId) external onlyOwner() {
This is actually the destinationChainId no?

2024-10-19 14:45 UTC, wsdt commented on contracts/LightBridge.sol
> +    mapping(uint32 => uint256) public percentExitFee;
As of today we set the fee based on the destinationChain (= where the smart contract is deployed). 

This actually means we could simply set the fee as simple uint256. Any route will be charged the fee when they want to receive funds on this network. 

E.g. Boba ETH -> ETH, as well as Boba BNB -> ETH would both have the fee this way which 100% maps the current behavior of the backend service.

2024-10-19 14:45 UTC, wsdt requested changes
left some feedback

2024-10-20 10:58 UTC, sk-enya commented on contracts/LightBridge.sol
> +    function setPercentExitFee(uint256 _percentExitFee, uint32 _sourceChainId) external onlyOwner() {
yeah, let me change the names. thank you for pointing out!

2024-10-20 10:58 UTC, sk-enya commented on contracts/LightBridge.sol
> +        uint256 _fee = _amount * percentFee / 10000;
Sure!

2024-10-20 11:02 UTC, sk-enya commented on contracts/LightBridge.sol
> +    mapping(uint32 => uint256) public percentExitFee;
I’ve set it up to function as it currently does, so I just need to rename it to destinationChainId.

The calculation process is the same; it’s just been moved to a separate function in the contract called calculateAmountAfterFee. This function performs the same task of calculating the fee if an exit fee is applicable for the destination chain and deducts it accordingly.

Please let me know if I’ve missed anything.

2024-10-21 09:26 UTC, wsdt requested changes
-

2024-10-21 09:26 UTC, wsdt commented on contracts/LightBridge.sol
> +    mapping(uint32 => uint256) public percentExitFee;
from a configuration perspective this gives more flexibility yes because we can set a different fee depending on where the funds come from: 

Boba BNB -> ETH, e.g. 1%
Boba ETH -> ETH, e.g. 2%

But the current backend implementation and the original use case make the fee dependent on the destinationChain not the sourceChain. Meaning: 

(Any network) -> ETH, e.g. 1%

This has 2 consequences: 
- Less flexibility yes (but for my understanding we don't need that, as we just want to tax people exiting or depending on the current network)

- Simpler smart contract, and way easier to keep track of fees and configuring where which fee applies. 


This way we would avoid setting the fee for each route/network. 

Feedback? @boyuan-chen @sk-enya

2024-10-21 12:24 UTC, sk-enya commented on contracts/LightBridge.sol
> +    mapping(uint32 => uint256) public percentExitFee;
I initially set up a single variable for the exit fee, but after talking with Boyuan, we realized we don’t want to charge fees for certain routes, like Boba BNB to Boba ETH and vice versa.

So, I’ve changed the implementation to allow for more flexibility. This way, if we want to support other chains in the future, like Boba BNB to BNB, it will be easier to adjust the fees.

The current setup lets us modify fees based on specific needs without having to keep separate configurations or redeploy services. Everything is now managed in the contract, making it easy to change and query when necessary during blocks.

eg:
```markdown
Boba BNB => Boba ETH => 0%
Boba BNB => BNB => 1%
Boba BNB => ETH Mainnet => 2%
```

2024-10-21 13:24 UTC, wsdt commented on contracts/LightBridge.sol
> +    mapping(uint32 => uint256) public percentExitFee;
the setup you described is actually the one I proposed for my understanding. No? 

Because you are using sourceChainIds.

2024-10-21 14:10 UTC, sk-enya commented on contracts/LightBridge.sol
> +    mapping(uint32 => uint256) public percentExitFee;
@wsdt can you please help what exactly needs be done or any changes needed in this?

2024-10-21 15:12 UTC, boyuan-chen commented
I am ok with this variable. It is more flexible.

2024-10-21 17:13 UTC, wsdt commented
> I am ok with this variable. It is more flexible.

ok!

2024-11-01 11:42 UTC, wsdt commented on contracts/LightBridge.sol
> +    mapping(uint32 => uint256) public percentExitFee;
as mentioned previously, in my mind the code is the other way round. 

This contract is deployed on Chain A. When disbursing an asset (where we deduct the fee) we are actually always on the same destinationChainId (the one where the contract is deployed). But instead we take the sourceChainId (where the funds come from) and use that in the mapping to determine the fee. 

So the fee is not dependent on the destinationChain but the sourceChain. Hence comments and namings are either partially off or it's in general not intentional. 

Originally the backend was actually dependent on the destination network. The target determined the fee, now the source determines the fee. 

Both are fine, but the naming and flow should be clear to avoid confusion.

2024-11-01 11:42 UTC, wsdt commented on contracts/LightBridge.sol
> +        percentExitFee[_destinationChainId] = _percentExitFee;
here for example

2024-11-01 11:43 UTC, wsdt commented on contracts/LightBridge.sol
> +    /// {destinationChainId} => {exitFee}
here for example

2024-11-01 11:45 UTC, wsdt commented on test/lightbridge.integration.spec.ts
> +      await LightBridge.setPercentExitFee(500, chainId)
This test is coding from Chain A to Chain A. Which is not a full test. 

We should use Chain A to Chain B (e.g. LightBridgeBNB as in other tests).

2024-11-01 11:45 UTC, wsdt commented on test/lightbridge.integration.spec.ts
> +      l2RpcProvider: new providers.JsonRpcProvider({
I guess this is not intentional and should be removed pls

2024-11-01 11:45 UTC, wsdt requested changes
left some comments

2024-11-01 20:41 UTC, sk-enya commented on contracts/LightBridge.sol
> +    mapping(uint32 => uint256) public percentExitFee;
Yeah, you are correct flow is working as expected I just messedup with comments and naming will fix resolve.

2024-11-01 20:42 UTC, sk-enya commented on contracts/LightBridge.sol
> +        percentExitFee[_destinationChainId] = _percentExitFee;
yups did that earlier intentionaly based on your earlier feedback which I miss understood I guess will revert it back.

2024-11-02 00:38 UTC, merged